version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      
    ports:
      - "3306:3306"
    volumes:
      - django_mysql_data:/var/lib/mysql

volumes:
  django_mysql_data:
